In [1]:
import pandas as pd

In [2]:
import numpy as np

In [9]:
st = pd.read_csv("50_Startups classwork.csv")

In [12]:
st.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [15]:
st['R&D Spend'].corr(st['Profit'])

0.9729004656594831

In [16]:
st.groupby('State')['Profit'].max()

State
California    191792.06
Florida       191050.39
New York      192261.83
Name: Profit, dtype: float64

In [17]:
st['Marketing Spend'].corr(st['Profit'])

0.7477657217414765

In [19]:
st.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [21]:
st['Administration'].corr(st['Profit'])

0.20071656826872136

In [23]:
st.groupby('State')['Profit'].mean()

State
California    103905.175294
Florida       118774.024375
New York      113756.446471
Name: Profit, dtype: float64

In [25]:
st.iloc[st['State'].idxmax()]

R&D Spend           165349.2
Administration      136897.8
Marketing Spend     471784.1
State               New York
Profit             192261.83
Name: 0, dtype: object

In [ ]:
st.loc